apps/calc/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField,IntegerField,DecimalField,FloatField,SelectField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo
from wtforms import ValidationError


class feetMeters(FlaskForm):
    feets = IntegerField('Feets', validators=[DataRequired()])
    inchs = DecimalField('Inchs', validators=[DataRequired()])
    resultado = StringField('Resultado', render_kw={'readonly': 'True'})
    submit = SubmitField('Calcula')

class presionForm(FlaskForm):
    pres_origen = FloatField('Origin Value', validators=[DataRequired()])
    unidad = SelectField('Unidad', choices=[('Bar', 'bar'), ('Psi', 'psi')], validators=[DataRequired()])
    submit = SubmitField('Calcula')





apps/calc/__init__.py

from flask import Blueprint

blueprint = Blueprint(
    'calc_blueprint',
    __name__,
    url_prefix='/calc'
)

apps/calc/routes.py
from flask import render_template, redirect, url_for,session, abort, flash, request,\
    current_app, make_response
from flask_login import login_required, current_user
from flask_sqlalchemy import get_debug_queries
#from apps.calc import calc
from apps.calc import blueprint
from .forms import feetMeters,presionForm
from flask_login import login_required, current_user
from jinja2 import TemplateNotFound
#import calculadoras as cal

import math

@blueprint.route('/')
def route_default():
    return redirect(url_for('calc_blueprint.acerca'))

@blueprint.route('/feetMeter', methods=['GET', 'POST'])
@login_required
def feetMeter():
    form = feetMeters()
    result= None
    
    if(form.validate_on_submit()):
        feet_origen= float(form.feets.data)
        inchs_origen= float(form.inchs.data)

        result = f"{feet_origen*0.3048 + inchs_origen*0.0254:.2f}"

        # Almacenar los campos en la cookie
        session['feet_origen'] = feet_origen
        session['inchs_origen'] = inchs_origen
        session['resultado'] = result

        return redirect(url_for('calc_blueprint.feetMeter'))

    # Rellenar los campos entre el formulario
    if( (session.get('feet_origen') is not None) and (session.get('inchs_origen') is not None) and (session.get('resultado') is not None) ):

        form.feets.data = float(session.get('feet_origen'))
        form.inchs.data = session.get('inchs_origen')
        form.resultado.data = session.get('resultado')

    return render_template('calc/feetsMeters.html', form=form,result=session.get('resultado'),title='Feet to Meters Conversion')

@blueprint.route('/pressure', methods=['GET', 'POST'])
@login_required
def pressure():

    form = presionForm()

    if(form.validate_on_submit()):

        pres_origen= form.pres_origen.data
        unidad= form.unidad.data
        if unidad=='Psi':
            result_ = pres_origen/14.5038
            rusult_str = f"{result_:.2f}"+ " bar"
        else:
            result_= pres_origen*14.5038
            rusult_str = f"{result_:.2f}"+ " psi"
        session['resultado'] = rusult_str
        session['unidad']= unidad
        session['pres_origen'] = pres_origen

        return redirect(url_for('calc_blueprint.pressure'))

    # Rellenar los campos entre el formulario

    form.unidad.data = session.get('unidad')
    form.pres_origen.data = session.get('pres_origen')

    return render_template('calc/presion.html', form=form,result=session.get('resultado'),title='Pressure Conversion')


@blueprint.route('/acerca', methods=['GET', 'POST'])
def acerca():

    return render_template('calc/about.html')


@blueprint.route("/temperatura")
def temperatura():
    return render_template("calc/temperatura.html")


@blueprint.route("/potencia")
def potencia():
    return render_template("calc/potencia_elec.html")



@blueprint.route('/convert', methods=['POST'])
def convert():
    temperature = float(request.form['temperature'])
    unit = request.form['unit']

    if unit == 'celsius':
        converted_temperature = float(temperature) + 273.15
        result = f"{temperature:.2f} °C is equal to {converted_temperature:.2f} K"

    elif unit == 'kelvin':
        converted_temperature = float(temperature) - 273.15
        result = f"{temperature:.2f} K is equal to {converted_temperature:.2f} °C"
    else:
        result = 'Invalid unit'
  
    return render_template('calc/temperatura.html', result=result)


@blueprint.route('/convertpot', methods=['POST'])
def convertpot():
    
    intput_usage=90.0

    potencia_input = (float)(request.form['potencia'])
    unit = request.form['unit']
    input_volt= (float)(request.form['voltaje'])
    intput_pf_cos= ((float)(request.form['pf']))/100

    if unit == 'kw':
        
        # Perform calculations to Kw
        converted_potencia =(potencia_input*1000/((math.sqrt(3)*input_volt)*math.cos(intput_pf_cos)))    
        result = f'{potencia_input} kw is equal to {converted_potencia:.2f} A'
        
    elif unit == 'amp':
        # Perform calculations to Amp(I)
        converted_potencia = (math.sqrt(3)*input_volt*potencia_input*math.cos(intput_pf_cos) /1000) 
        result = f'{potencia_input} A is equal to {converted_potencia:.2f} Kw'
        
    else:
        result = 'Invalid unit'

    return render_template('calc/potencia_elec.html', result=result)

apps/templates/calc/about.html
{% extends "layouts/base.html" %}


{% block title %} Informacion del sitio webApp Calculadoras {% endblock %}

{% block router_content %}
<li class="breadcrumb-item active" aria-current="page">
  About</li>
{% endblock %}


{% block page_content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="page-header" style="text-align: center;" >
  <h2> Realizada por Valtic & Prog. Salkman</h2>
  <p> Pagina para aglutinar herramientas y calculadoras diseñada en Python y Flask </p>
  <p> Basado en el Dashboard Admin Volt de AppSeed y Themesberg</p>
  <p> Copyright © 2024 
  </p> 
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>  
<br>
<br>

{% endblock %}

apps/templates/calc/feetsMeters.html
{% extends "layouts/base.html" %}
{% import "bootstrap/form.html" as wtf %}

{% block title %}{% if title %} {{title}} {% else %} <p>Calculadoras V4 by Valtic - Feets </p>{% endif %}  {% endblock %}

{% block router_content %}
<li class="breadcrumb-item active" aria-current="page">
    Longitud</li>
{% endblock %}

{% block page_content %}

<div class="feetsMeter-form">
    <h1>Feet to Meters Conversion 2023</h1>
    {{ wtf.render_form(form) }}
    
    <h2>Feet to Meters Conversion Result:</h2>

    {% if result %}
        <p>{{ result }}</p>
    {% endif %}


</div>


<nav class="pagination">
    <span class="prev"><a href="{{url_for('calc_blueprint.temperatura')}}">Temperatura</a></span>
    <span class="next"><a href="{{url_for('calc_blueprint.pressure')}}">Presion</a></span>
</nav>

{% endblock %}

{% block scripts %}
<script>
    let input = document.getElementById('resultado');
    function clearResult(event) {
       // access input field
       let output = document.getElementById('resultado');
       // clear the input field.
       output.value = "";
    }


    var myField = document.getElementById("feets");
    myField.oninput = clearResult;
    var myField = document.getElementById("inchs");
    myField.oninput = clearResult;

</script>
{% endblock %}

apps/templates/calc/potencia_elec.html
{% extends "layouts/base.html" %}


{% block title %}{% if title %} {{title}} {% else %} Calculadoras V4 by Valtic - Pot. Electrica {% endif %}  {% endblock %}

{% block router_content %}
<li class="breadcrumb-item active" aria-current="page">
    Potencia Electrica</li>
{% endblock %}


{% block page_content %}

<div class="potelec-form">

    <h1>Electric Power Conversion</h1>
    <form class=Form action="convertpot" method="POST">
        <div class="form-group required">  
            <label class="form-control-label"  for="Voltage">Voltaje:</label>
            <input class="form-control" type="number" name="voltaje" id="voltaje"  value="380" required>
        </div>
        <div class="form-group required">  
            <label class="form-control-label" for="powerFactor">Power Factor:</label>
            <input class="form-control" type="float" name="pf" id="pf"  value="85" required>
        </div>
        <div class="form-group required">  
            <label class="form-control-label" for="Potencia">Potencia:</label>
            <input class="form-control" type="number" name="potencia" id="potencia" required>
        </div>

        <div class="form-group required">  
            <label class="form-control-label" for="unit">Unit:</label>
            <select class="form-control" name="unit" id="unit" required>
                <option value="kw">Kw/h</option>
                <option value="amp">Amp</option>
            </select>
        </div>
        <input class="btn btn-primary btn-md" type="submit" value="Convertir">
    </form>
    
    <h2>Electric Power Conversion Result:</h2>

    {% if result %}
        <p>{{ result }}</p>
    {% endif %}


</div>

<nav class="pagination">
    <span class="prev"><a href="{{url_for('calc_blueprint.potencia')}}">Potencia</a></span>
    <span class="next"><a href="{{url_for('calc_blueprint.potencia')}}">Potencia</a></span>
</nav>

{% endblock %}

apps/templates/calc/presion.html
{% extends "layouts/base.html" %}
{% import "bootstrap/form.html" as wtf %}

{% block title %}{% if title %} {{title}} {% else %} <p>Calculadoras V4 by Valtic - Presión </p>{% endif %}  {% endblock %}

{% block router_content %}
<li class="breadcrumb-item active" aria-current="page">
    Presion</li>
{% endblock %}

{% block page_content %}

<div class="presion-form">
    <h1>Conversion de Presion</h1>
    {{ wtf.render_form(form) }}
    
    <h2>Resultado:</h2>
    {% if result %}
        <p>{{ result }}</p>
    {% endif %}

</div>


<nav class="pagination">
    <span class="next"><a href="{{url_for('calc_blueprint.feetMeter')}}">Longitud</a></span>
    <span class="next"><a href="{{url_for('calc_blueprint.temperatura')}}">Temperatura</a></span>
</nav>

{% endblock %}

apps/templates/calc/temperatura.html
{% extends "layouts/base.html" %}

{% block title %}{% if title %} {{title}} {% else %} Calculadoras V4 by Valtic - Feets {% endif %}  {% endblock %}

{% block router_content %}
    <li class="breadcrumb-item active" aria-current="page">
    Temperatura</li>
{% endblock %}

{% block page_content %}

<div class="temp-form">

    <h1>Temperature Conversion</h1>
    <form class=Form action="convert" method="POST">
        <div class="form-group required">      
            <label class="form-control-label" for="temperature">Temperature:</label>
            <input class="form-control" type="number" name="temperature" id="temperature" required>    
        </div>

        <div class="form-group required">   
            <label class="form-control-label" for="unit">Unit:</label>
            <select class="form-control"  name="unit" id="unit" required>
                <option value="celsius">Celsius</option>
                <option value="kelvin">Kelvin</option>
            </select>
         </div>

        <input class="btn btn-primary btn-md" id="submit"  type="submit" value="Convertir">
    </form>
    
    <h2>Temperature Conversion Result:</h2>

    {% if result %}
        <p>{{ result }}</p>
    {% endif %}


    <nav class="pagination">
        <span class="prev"><a href="{{url_for('calc_blueprint.pressure')}}">Presion</a></span>
        <span class="next"><a href="{{url_for('calc_blueprint.feetMeter')}}">Longitud</a></span>
    </nav>

</div>



{% endblock %}